### ISSUE TITLE
error [-Wunused-variable] U8glib

### ISSUE THREAD

**Issue by Rod3d** [atom/.github#12]
When trying to compile in ATOM 1.41.0 x 64 using a platformio ide extension, I receive an error [-Wunused-variable]. The file in question comes from Marlin Github "Marlin-bugfix-2.0.x". I beleive the path is (Marlin-bugfix-2.0.x/Marlin/src/HAL/HAL_AVR/u8g_com_HAL_AVR_sw_sp.cpp). The exact error (which does not keep me from compiling successfully) is;
.pio\libdeps\LPC1768\U8glib-HAL_ID1932\src\clib\U8g_com_i2c.c:44:16: warning:  'u8g_i2c_opt' defined but not used [-Wunused-variable] static uint8_t u8g_i2c_opt;  /* U8G_I2C_OPT_NO_ACK, SAM: U8G_I2C_OPT_DEV_1 */
The files compile successfully, but when trying to compile in Arduino Marlin with the Marlin.ino file, I receive the following error and cannot compile. 
Arduino: 1.8.10 (Windows 10), Board: "Arduino/Genuino Uno"

D:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware D:\Program Files (x86)\Arduino\hardware -tools D:\Program Files (x86)\Arduino\tools-builder -tools D:\Program Files (x86)\Arduino\hardware\tools\avr -built-in-libraries D:\Program Files (x86)\Arduino\libraries -libraries C:\Users\Rods account\Documents\Arduino\libraries -fqbn=arduino:avr:uno -ide-version=10810 -build-path C:\Users\RODSAC~1\AppData\Local\Temp\arduino_build_534461 -warnings=none -build-cache C:\Users\RODSAC~1\AppData\Local\Temp\arduino_cache_382076 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=D:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.avr-gcc-7.3.0-atmel3.6.1-arduino5.path=D:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.arduinoOTA.path=D:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.arduinoOTA-1.3.0.path=D:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.avrdude.path=D:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.avrdude-6.3.0-arduino17.path=D:\Program Files (x86)\Arduino\hardware\tools\avr -verbose C:\Users\Rods account\Desktop\3D printer\Marlin-bugfix-2.0.x\Marlin\Marlin.ino
D:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware D:\Program Files (x86)\Arduino\hardware -tools D:\Program Files (x86)\Arduino\tools-builder -tools D:\Program Files (x86)\Arduino\hardware\tools\avr -built-in-libraries D:\Program Files (x86)\Arduino\libraries -libraries C:\Users\Rods account\Documents\Arduino\libraries -fqbn=arduino:avr:uno -ide-version=10810 -build-path C:\Users\RODSAC~1\AppData\Local\Temp\arduino_build_534461 -warnings=none -build-cache C:\Users\RODSAC~1\AppData\Local\Temp\arduino_cache_382076 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.avr-gcc.path=D:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.avr-gcc-7.3.0-atmel3.6.1-arduino5.path=D:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.arduinoOTA.path=D:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.arduinoOTA-1.3.0.path=D:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.avrdude.path=D:\Program Files (x86)\Arduino\hardware\tools\avr -prefs=runtime.tools.avrdude-6.3.0-arduino17.path=D:\Program Files (x86)\Arduino\hardware\tools\avr -verbose C:\Users\Rods account\Desktop\3D printer\Marlin-bugfix-2.0.x\Marlin\Marlin.ino
Using board 'uno' from platform in folder: D:\Program
Using core 'arduino' from platform in folder: D:\Program
Detecting libraries used...
"D:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-ID:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-ID:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\standard" "C:\\Users\\RODSAC~1\\AppData\\Local\\Temp\\arduino_build_534461\\sketch\\Marlin.ino.cpp" -o nul
"D:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-ID:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-ID:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\standard" "C:\\Users\\RODSAC~1\\AppData\\Local\\Temp\\arduino_build_534461\\sketch\\src\\HAL\\HAL_AVR\\HAL.cpp" -o nul
Error while detecting libraries included by C:\Users\RODSAC~1\AppData\Local\Temp\arduino_build_534461\sketch\src\HAL\HAL_AVR\HAL.cpp
"D:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-ID:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-ID:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\standard" "C:\\Users\\RODSAC~1\\AppData\\Local\\Temp\\arduino_build_534461\\sketch\\src\\HAL\\HAL_AVR\\HAL_SPI.cpp" -o nul
Error while detecting libraries included by C:\Users\RODSAC~1\AppData\Local\Temp\arduino_build_534461\sketch\src\HAL\HAL_AVR\HAL_SPI.cpp
"D:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-ID:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-ID:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\standard" "C:\\Users\\RODSAC~1\\AppData\\Local\\Temp\\arduino_build_534461\\sketch\\src\\HAL\\HAL_AVR\\MarlinSerial.cpp" -o nul
Error while detecting libraries included by C:\Users\RODSAC~1\AppData\Local\Temp\arduino_build_534461\sketch\src\HAL\HAL_AVR\MarlinSerial.cpp
"D:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-ID:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-ID:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\standard" "C:\\Users\\RODSAC~1\\AppData\\Local\\Temp\\arduino_build_534461\\sketch\\src\\HAL\\HAL_AVR\\Servo.cpp" -o nul
Error while detecting libraries included by C:\Users\RODSAC~1\AppData\Local\Temp\arduino_build_534461\sketch\src\HAL\HAL_AVR\Servo.cpp
"D:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-ID:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-ID:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\standard" "C:\\Users\\RODSAC~1\\AppData\\Local\\Temp\\arduino_build_534461\\sketch\\src\\HAL\\HAL_AVR\\fast_pwm.cpp" -o nul
"D:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-ID:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-ID:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\standard" "C:\\Users\\RODSAC~1\\AppData\\Local\\Temp\\arduino_build_534461\\sketch\\src\\HAL\\HAL_AVR\\fastio.cpp" -o nul
"D:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-ID:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-ID:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\standard" "C:\\Users\\RODSAC~1\\AppData\\Local\\Temp\\arduino_build_534461\\sketch\\src\\HAL\\HAL_AVR\\persistent_store_eeprom.cpp" -o nul
Error while detecting libraries included by C:\Users\RODSAC~1\AppData\Local\Temp\arduino_build_534461\sketch\src\HAL\HAL_AVR\persistent_store_eeprom.cpp
"D:\\Program Files (x86)\\Arduino\\hardware\\tools\\avr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10810 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR "-ID:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\cores\\arduino" "-ID:\\Program Files (x86)\\Arduino\\hardware\\arduino\\avr\\variants\\standard" "C:\\Users\\RODSAC~1\\AppData\\Local\\Temp\\arduino_build_534461\\sketch\\src\\HAL\\HAL_AVR\\u8g_com_HAL_AVR_sw_spi.cpp" -o nul
Alternatives for U8glib.h: []
C:\Users\RODSAC~1\AppData\Local\Temp\arduino_build_534461\sketch\src\HAL\HAL_AVR\u8g_com_HAL_AVR_sw_spi.cpp:65:10: fatal error: U8glib.h: No such file or directory
ResolveLibrary(U8glib.h)

 #include <U8glib.h>

  -> candidates: []          ^~~~~~~~~~

compilation terminated.

exit status 1
Error compiling for board Arduino/Genuino Uno.

I have deleted and redownloaded the github version and recompiled in ATOM platformio IDE and no longer receive the error: (.pio\libdeps\LPC1768\U8glib-HAL_ID1932\src\clib\U8g_com_i2c.c:44:16: warning:  'u8g_i2c_opt' defined but not used [-Wunused-variable] static uint8_t u8g_i2c_opt;  /* U8G_I2C_OPT_NO_ACK, SAM: U8G_I2C_OPT_DEV_1 */) while compiling. However, I still get the error in Arduino and am unable to compile. I have posted this problem on the Arduino boards as well. I am a beginner and cannot determine from where this error has originated, or how to fix it as I am not a coder. 
Thanks in advance for any help that you might give me.

**Comment by Arcanemagus** [comment]
This appears to be a PlatformIO IDE issue, you should probably be contacting them for support as it doesn't appear to have anything to do with the Atom text editor.

Thanks for reaching out!

----

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us halfway :grinning:
