### ISSUE TITLE
Pull request template - report some broken links

### ISSUE THREAD

**Issue by antleblanc** [atom/.github#9]
### Description

File impacted: `.github/PULL_REQUEST_TEMPLATE.md`:

The following links return an error `404: Not Found`:
- https://bit.ly/atom-bugfix
- https://bit.ly/atom-perf
- https://bit.ly/atom-docs
- https://bit.ly/atom-behavior

### Steps to Reproduce

1. Go to: https://github.com/atom/.github/blob/master/PULL_REQUEST_TEMPLATE.md
2. See the broken links

**Expected behavior:**

All links should be fixed.

**Actual behavior:**

All links are broken.

**Reproduces how often:**

Always reproduce the issue.

**Comment by rsese** [comment]
Thanks @antleblanc!  Looks like all the links are missing the `-pr` at the end - for example, `https://bit.ly/atom-bugfix` should be `https://bit.ly/atom-bugfix-pr` (see the working links in [atom/atom](https://github.com/atom/atom/blob/ef80c4d43880571f566b18b2ec497d7c09011968/PULL_REQUEST_TEMPLATE.md)).

Would you like to open a pull request to fix these up @antleblanc?

**Comment by antleblanc** [comment]
Thanks @rsese!

Here is the attached Pull Request: https://github.com/atom/.github/pull/10
